### ISSUE TITLE
Fix: handle connexion bomb company with different countries

### ISSUE THREAD

**Issue by Nathanlauga** [dataforgoodfr/CarbonBombs#47]
There are 4 bombs with multiple countries (multiple rows for one bomb). In the connexion_bomb_company if we cumulate the percentage it's more than 100%

We need to find how to handle that problem.

**Comment by mnicolleUTC** [comment]
At the end the percentage is not problematic because for these bombs with multiple countries it's either "No informations on company" either "New project". As there is no companies with this name, the relationship is not created under neo4j. Still I create a protection in the relation query to avoid this mistake.
