### ISSUE TITLE
Fusionner les 3 entreprises "OXY USA", "Occidental Petroleum Corporation" et "Occidental Permian" 

### ISSUE THREAD

**Issue by OrianeWgn** [dataforgoodfr/CarbonBombs#84]
Les 3 entreprises "OXY USA", "Occidental Petroleum Corporation" et "Occidental Permian" sont en réalité la même entreprise. Les fusionner permettra de consolider ses 3 bombes + les émissions totales, et le financement bancaires aux trois projets

**Comment by mnicolleUTC** [comment]
Those name are differents denomination for GEM database. On BOCC side the name is Occidental Petroleum Corp. So in order to merge those companies, we must add 3 key pair values in manual_match_company dictionary in manual_match.py where keys = those 3 GEM names and Values always equal to Occidental Petroleum Corp. Google Sheet will also be updated in consequence
